name: Semgrep Scan

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  semgrep-scan:
    name: Scan codebase with Semgrep
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      
    - name: Install Semgrep
      run: |
        curl -L https://semgrep.dev/install.sh | sh
        export PATH=$HOME/.local/bin:$PATH

    - name: Verify Semgrep installation
      run: semgrep --version

    - name: Run Semgrep
      run:  semgrep --config=p/r2c/python-security main.py
         
        
    - name: Upload Semgrep results
      if: always()  # Upload results even if Semgrep fails
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-results
        path: results.json  # Adjust path to Semgrep results file
