name: Semgrep Scan

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  semgrep-scan:
    name: Scan codebase with Semgrep
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Semgrep
      run: |
        curl -L https://semgrep.dev/install.sh | sh
        export PATH=$HOME/.local/bin:$PATH
      
    - name: Run Semgrep
      run: |
        semgrep --config=p/r2c/python-security main.py  # Adjust command and files to scan
        
    - name: Upload Semgrep results
      if: always()  # Upload results even if Semgrep fails
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-results
        path: results.json  # Adjust path to Semgrep results file
